server:
  port: 17000
spring:
  application:
    name: bj-sms
  rabbitmq:
    host: 192.168.74.111
    username: leyou
    password: leyou
    virtual-host: /leyou
bajie:
  sms:
    accessKeyId: JWffwFJIwada # 你自己的accessKeyId
    accessKeySecret: aySRliswq8fe7rF9gQyy1Izz4MQ # 你自己的AccessKeySecret
    signName: 八戒商城 # 签名名称
    verifyCodeTemplate: SMS_133976814 # 模板名称


#    SMS_143714980
#    HKUIDl21ZM7XoubErXjUFJq84dha8W
#    LTAItNxtDfk7MJMq
