server:
  port: 15000
spring:
  rabbitmq:
    host: 192.168.74.111
    username: leyou
    password: leyou
    virtual-host: /leyou
  main:
    allow-bean-definition-overriding: true
  application:
    name: bj-page
  thymeleaf:
    cache: false
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
